services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 8080
    ports:
      - "4000:8080"
    environment:
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - UWSGI_HTTP=0.0.0.0:8080
      - SEARXNG_BASE_URL=http://localhost:4000/
    volumes: # Add this section
      - ./searxng-settings.yml:/etc/searxng/settings.yml # Mount local settings file
    networks:
      - future-search
  future-search-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose: # Internal port the app listens on
      - 3001 
    ports: # Map host port 3002 to container's internal port 3001
      - "3002:3001" 
    networks:
      - future-search

  future-search-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3002
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3002/api
    depends_on:
      - future-search-backend
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - future-search

networks:
  future-search:
